"""Abstract base class for trading strategies."""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Any

import pandas as pd


class SignalType(Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_SIGNAL = "NO_SIGNAL"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    type: SignalType
    symbol: str
    entry_price: float
    stop_loss: float
    take_profit: float
    duration_seconds: int
    confidence: float  # 0.0 to 1.0
    metadata: dict[str, Any] | None = None

    def __post_init__(self) -> None:
        if self.metadata is None:
            self.metadata = {}


class Strategy(ABC):
    """Abstract base for all trading strategies."""

    def __init__(self, name: str, symbol: str):
        self.name = name
        self.symbol = symbol

    @abstractmethod
    def generate_signal(self, data: pd.DataFrame) -> Signal:
        """
        Analyze data and generate a trading signal.

        Args:
            data: DataFrame with OHLCV columns (epoch, open, high, low, close)

        Returns:
            Signal with entry/exit/stop or NO_SIGNAL
        """
        ...

    @abstractmethod
    def get_win_probability(self, signal: Signal) -> float:
        """Estimate win probability for Kelly sizing."""
        ...
